version: '3.8'
services:
  redis_cache:
    image: redis
    networks:
      - cunyhacks-net
  backend:
    build: ./backend
    networks:
      - cunyhacks-net
  frontend1:
    build: ./frontend1
    networks:
      - cunyhacks-net

networks:
  cunyhacks-net:
    driver: host