version: '3.8'
services:
  redis_cache:
    image: redis
    network_mode: host
  backend:
    build: ./backend
    network_mode: host
  gateway:
    build: ./gateway
    network_mode: host
  frontend1:
    build: ./frontend1
    network_mode: host
  frontend2:
    build: ./frontend2
    network_mode: host